name: 04 - Using Actions

on: 
   workflow_dispatch:


jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: chekout code
              uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/checkout@v4
              with:
                node-version: '20.x'
            
            


