name: 05-1 filters and activity types

on:
    workflow_dispatch:
#    push:
#          branches: 
#          - main
#          - opened 
#          - synchronize
#    pull_request:
#          types: [opened, synchronize, closed, edited, labeled]


jobs: 
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: echo job
        run: echo "Running whenever a PR is opened or syncronized AND base branch is main"
         