name: 09 - Using Functions

on:
    pull_request:
    workflow_dispatch:


jobs:
    echo1:
        runs-on: ubuntu-latest
        steps:
         - name: Print PR title
           run: echo "${{ github.event.pull_request.title }}"
         - name: Print labels
           run: |
            cat << EOF
            %{{ toJSON (github.event.pull_request.labels)}}
            EOF
         - name: Bug step
           if: ${{ !cancelled() && contains(github.event.pull_request.title, 'fix') }}
           run: echo "Bug fix"
         - name: Failing Step
           run: exit 1 
         - name: I will be skipped
           if: ${{ success () }}
           run: echo " print if previous step succeeds"
         - name: I will execute
           if: ${{ failure ()}}
           run: echo "print if previous step fails"
         - name: I will execute
           if: ${{ !cancelled() }}
           run: echo " Always print, execpt when. the workflow is cancelled"
         - name: I will execute when cancelled
           if: ${{ !cancelled() }}
           run: echo " Always print, execpt when. the workflow is cancelled"

                
