name: 14 - working with Artifacts


on:
    workflow_dispatch:



jobs:
    test-build:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: 14-artifacts/my-react-app-14artifacts
        steps:
            - name: checkout code
              uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                node-version: 25.x
            - name: Download Cached dependencies
              uses: actions/cache@v4
              id: cache
              with:
                  path: 14-artifacts/my-react-app-14artifacts/app
                  key: deps-node-modules-${{ hashFiles('14-artifacts/my-react-app-14artifacts/package-lock.json') }}            
            - name: Install dependencies
              if: steps.cache.outputs.cache-hit != 'true'
              run: npm ci    
            - name: Unit Tests
              run: npm run test
            - name: Build code
              run: npm run build
            - name: Upload Build
              uses: actions/upload-artifact@v4
              with:
                name: app
                path: 14-artifacts/my-react-app-14artifacts/app/
    deploy: 
        runs-on: ubuntu-latest
        needs: test-build
        steps:
          - name: Download Build Artifact
            uses: actions/download-artifact@v4
            with:
              name: app
              path: build
          - name: Show folder structure
            run: ls -R
        
        