name: 18- Custom Actions - Docker
run-name: 18- Custom Actions 

on:
  workflow_dispatch:
          inputs:
            url:
              type: choice
              description: 'The URL to ping.'
              options:
                - 'https://www.github.com'
                - 'https://www.google.com'
                - 'https://www.python.org'
                - 'https:/invalid.url.test'
              default: 'https://www.github.com'
            max_trials:
              type: choice
              description: 'Maximum number of trials until action fails.'
              required: false
              options:
                - '5'
                - '10'
                - '15'
              default: '10'
            delay:
              description: 'Delay in seconds between trials.'
              required: false
              type: choice
              options:
                - '5'
                - '10'
                - '15'
              default: '5'
            
                

permissions:
  contents: write
  pull-requests: write


jobs:
    ping-url:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v6
            - name: Ping URL
              uses: ./.github/actions/docker-ping-url
              with:
                url: ${{ inputs.url }}
                max_trials: ${{ inputs.max_trials }}
                delay: ${{ inputs.delay }}
          
            

                