name: 20.2 - reusable-workflows
run-name: 20.2 - reusable-workflows

on: 
  workflow_dispatch:


jobs:
    deploy:
        uses: ./.github/workflows/20-reusable-workflows.yaml
        with:
          target-directory: placeholder-directory
    e2e-tests:
        uses: babypoet/Cypress-E2E-testing-project/.github/workflows/e2e.yaml
        needs: deploy
        
        

    